---

- name: webserver setup
  hosts: webservers
  become: yes
  tasks: 
    - name: installing service
      ansible.builtin.yum: 
          name: httpd
          state: absent
    
    - name: enable service
      ansible.builtin.service:
          name: httpd
          state: started
          enabled: yes
    
    - name: copying index.html file
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html

- name: dbserver setup
  hosts: dbservers
  become: yes
  tasks: 
    - name: installing maria-db service
      ansible.builtin.yum:
        name: mariadb-server
        state: absent

    - name: enable service
      ansible.builtin.service:
          name: mariadb
          state: started
          enabled: yes

